### ISSUE TITLE
Project Config support?

### ISSUE THREAD

**Issue by michaelroper** [verbb/buttonbox#29]
Hey team! Just wondering, is there anything on the roadmap for this plugin to support the Craft 3.1 Project Config feature, so that field settings can be saved into the project.yaml file and synced between environments?

**Comment by adrienne** [comment]
@Kashkin @lindseydiloreto Any progress on this? I'd really like to use it on a new project but i need config support!

**Comment by lindseydiloreto** [comment]
Hey @adrienne, I'm not really responsible for Button Box, generally speaking. I added the "Triggers" functionality, but outside of maintaining that feature, I don't actually contribute to this plugin at all.

To be honest, I may someday extract that Triggers functionality into a separate plugin. Button Box doesn't tend to get much love, it's been handled by a random series of developers since Josh left the company. I'm not really sure who is in charge of it anymore.

**Comment by adrienne** [comment]
@lindseydiloreto - if you're interested in forking the whole plugin *including* Triggers, i would be willing to help with that!

**Comment by lindseydiloreto** [comment]
Interesting proposition @adrienne... let me think about that. If I did fork this plugin, I'd keep the fork private. I'm not interested in publicly maintaining my own version of it.

I'll DM you on Discord!

**Comment by engram-design** [comment]
Not sure where this conversation trailed off to @lindseydiloreto and @adrienne but ButtonBox, like every other Craft field is supported by project config whether you want to or not!

**Comment by lindseydiloreto** [comment]
Good to know, thanks @engram-design! Really glad to see that Verbb has acquired Button Box, it gives me hope for the future of it. 🙂
